var nodes = 
{
	nodes: [
		{
			groupId: 'group1',
			outlineWidth: 1,
			outlineColor: 'red',
			childrens: [
				{
					id: 'group1_node1',
					type: 'node',
					/*name: '调度数据网',*/
					name2: '调度数据网',
					image: 'title',
					x: 700,
					y: 50,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_node2',
					type: 'node',
					/*name: '纵向加密装置',*/
					name2: '纵向加密装置',
					image: 'test_rect',
					x: 800,
					y: 150,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_node3',
					type: 'node',
					name: '非控制区交换机',
					name2: null,
					image: 'sb2',
					x: 885,
					y: 300,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_node4',
					type: 'node',
					name: '横向防火墙',
					name2: null,
					image: 'sb1',
					x: 750,
					y: 300,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_node5',
					type: 'node',
					name: '控制区交换机',
					name2: null,
					image: 'sb2',
					x: 600,
					y: 300,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_node6',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 200,
					y: 200,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group1_node6_1',
							image: 'sb1',
							x: 200,
							y: 300,
						},
						{
							id: 'group1_node6_2',
							image: 'sb1',
							name: '172.168.170.22',
							linkName: '一区综合演示',
							x: 250,
							y: 300,
						},
						{
							id: 'group1_node6_3',
							image: 'sb2',
							x: 300,
							y: 300,
						},
						{
							id: 'group1_node6_34',
							image: 'sb1',
							x: 350,
							y: 300,
						},
					]
				},
				{
					id: 'group1_node7',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 200,
					y: 400,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group1_node7_1',
							image: 'sb1',
							x: 200,
							y: 500,
						},
						{
							id: 'group1_node7_2',
							image: 'sb1',
							name: '172.168.170.22',
							x: 250,
							y: 500,
						},
						{
							id: 'group1_node7_3',
							image: 'sb2',
							x: 300,
							y: 500,
						},
						{
							id: 'group1_node7_34',
							image: 'sb1',
							x: 350,
							y: 500,
						},

					]
				},
				{
					id: 'group1_node8',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 1100,
					y: 200,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group1_node8_1',
							image: 'sb1',
							x: 1100,
							y: 300,
						},
						{
							id: 'group1_node8_2',
							image: 'sb1',
							x: 1150,
							y: 300,
						},
						{
							id: 'group1_node8_3',
							image: 'sb2',
							x: 1200,
							y: 300,
						},

					]
				},
				{
					id: 'group1_node9',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 1100,
					y: 400,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group1_htmlNode1',
					type: 'htmlNode',
					name: '<div class="title_text">I区网络安全态势</br>感知采集装置</div>',
					/*name2: '我是name22',*/
					image: 'titleTop',
					x: 1100,
					y: 500,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
			]
		},
		{
			groupId: 'group2',
			outlineWidth: 1,
			outlineColor: '#ccc',
			childrens: [
				{
					id: 'group2_node1',
					type: 'node',
					/*name: '调度数据网',*/
					name2: '综合业务数据网',
					image: 'title',
					x: 1800,
					y: 50,
					labelPosition: 'bottom.bottom',
					labelFont: '18px arial',
					labelColor: 'red',
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group2_node2',
					type: 'node',
					/*name: '综合数据网',*/
					name2: '综合数据网',
					image: 'sb2',
					x: 2050,
					y: 300,
					labelPosition: 'top.top',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group2_node3',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 1700,
					y: 200,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group2_node4',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 1700,
					y: 300,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group2_node5',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan2',
					x: 1700,
					y: 500,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
				},
				{
					id: 'group2_node6',
					type: 'htmlNode',
					name: '<div class="title_text">III区网络安全态势</br>感知采集装置</div>',
					/*name2: '我是name22',*/
					image: 'titleTop',
					x: 1500,
					y: 285,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
			]
		},
		{
			groupId: 'group3',
			outlineWidth: 0,
			outlineColor: '#ccc',
			childrens: [
				{
					id: 'group3_htmlNode1',
					type: 'htmlNode',
					name: '<div class="left_title">站控层A网</div>',
					/*name2: '我是name22',*/
					image: null,
					x: 100,
					y: 650,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group3_htmlNode2',
					type: 'htmlNode',
					name: '<div class="left_title">站控层B网</div>',
					/*name2: '我是name22',*/
					image: null,
					x: 100,
					y: 850,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group3_htmlNode3',
					type: 'htmlNode',
					name: '<div class="left_title">站控层C网</div>',
					/*name2: '我是name22',*/
					image: null,
					x: 100,
					y: 1050,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group3_htmlNode4',
					type: 'htmlNode',
					name: '<div class="danBox">198.120.0.21-99</br>198.120.0.21-99</br>合计79</br>...</div>',
					/*name2: '我是name22',*/
					image: null,
					x: 300,
					y: 1100,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group3_htmlNode5',
					type: 'htmlNode',
					name: '<div class="danBox">198.120.0.21-99</br>198.120.0.21-99</br>合计79</br>...</div>',
					/*name2: '我是name22',*/
					image: null,
					x: 500,
					y: 1100,
					labelPosition: 'center',
					label2Position: 'bottom.bottom',
				},
				{
					id: 'group3_node1',
					type: 'node',
					name: 'VLAN1：198.120.0.0/16',
					name2: null,
					image: 'vlan',
					x: 200,
					y: 650,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group3_node1_1',
							image: 'sb1',
							x: 200,
							y: 750,
						},
						{
							id: 'group3_node1_2',
							image: 'sb1',
							name: '172.168.170.22',
							linkName: '电源箱',
							x: 250,
							y: 750,
						},
						{
							id: 'group3_node1_3',
							image: 'sb2',
							x: 300,
							y: 750,
						},
						{
							id: 'group3_node1_4',
							image: 'sb1',
							x: 350,
							y: 750,
						},
					]
				},
				{
					id: 'group3_node2',
					type: 'node',
					name: 'VLAN2：198.120.0.0/16',
					name2: null,
					image: 'vlan',
					x: 200,
					y: 850,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group3_node2_1',
							image: 'sb1',
							x: 200,
							y: 950,
						},
						{
							id: 'group3_node2_2',
							image: 'sb1',
							name: '172.168.170.22',
							linkName: '电源箱',
							x: 250,
							y: 950,
						},
						{
							id: 'group3_node2_3',
							image: 'sb2',
							x: 300,
							y: 950,
						},
						{
							id: 'group3_node2_4',
							image: 'sb1',
							x: 350,
							y: 950,
						},
					]
				},
				{
					id: 'group3_node3',
					type: 'node',
					name: 'VLAN3：198.120.0.0/16',
					name2: null,
					image: 'vlan',
					x: 200,
					y: 1000,
					labelPosition: 'center',
					labelFont: '18px arial',
					labelColor: null,
					label2Position: 'center',
					label2Font: '24px arial',
					label2Color: 'green',
					children: [
						{
							id: 'group3_node3_1',
							image: 'sb1',
							x: 200,
							y: 1200,
						},
						{
							id: 'group3_node3_2',
							image: 'sb1',
							name: '测控装置',
							x: 250,
							y: 1200,
						},
						{
							id: 'group3_node3_3',
							image: 'sb1',
							x: 300,
							y: 1200,
						},
						{
							id: 'group3_node3_4',
							image: 'sb1',
							x: 350,
							y: 1200,
						},
						{
							id: 'group3_node3_5',
							image: 'sb2',
							x: 400,
							y: 1200,
						},
						{
							id: 'group3_node3_6',
							image: 'sb2',
							name: '测控装置',
							x: 450,
							y: 1200,
						},
						{
							id: 'group3_node3_7',
							image: 'sb2',
							x: 500,
							y: 1200,
						},
						{
							id: 'group3_node3_8',
							image: 'sb2',
							x: 550,
							y: 1200,
						},
					]
				},
			]
		},

	],
	links: [
		{
			id:'1',
			color: 'red',
			fromPosition: 'bottom.bottom',
			fromNode: 'group1_node1',
			toNode: 'group1_node2'
		},
		{
			id:'2',
			color: 'green',
			fromNode: 'group1_node2',
			toNode: 'group1_node3'
		},
		{
			id:'3',
			color: '#333',
			fromNode: 'group1_node3',
			toNode: 'group1_node4'
		},
		{
			id:'4',
			fromNode: 'group1_node4',
			toNode: 'group1_node5'
		},
		{
			id:'5',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group1_node5',
			toNode: 'group1_node6'
		},
		{
			id:'6',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group1_node5',
			toNode: 'group1_node7'
		},
		{
			id:'7',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: 10,
			fromNode: 'group1_node3',
			toNode: 'group1_node8'
		},
		{
			id:'8',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			fromXoffset: 10,
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group1_node3',
			toNode: 'group1_node9'
		},
		//右侧分区连线 
		{
			id:'21',
			color: 'red',
			fromXoffset: 65,
			fromPosition: 'bottom.bottom',
			fromNode: 'group2_node1',
			toNode: 'group2_node2'
		},
		{
			id:'22',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group2_node2',
			toNode: 'group2_node3'
		},
		{
			id:'23',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group2_node2',
			toNode: 'group2_node4'
		},
		{
			id:'24',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group2_node2',
			toNode: 'group2_node5'
		},
		{
			id:'25',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group2_node6',
			toNode: 'group2_node3'
		},
		{
			id:'26',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group2_node6',
			toNode: 'group2_node4'
		},
		{
			id:'27',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group2_node6',
			toNode: 'group2_node5'
		},
		{
			id:'28',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group1_htmlNode1',
			toNode: 'group3_node1'
		},
		{
			id:'29',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group1_htmlNode1',
			toNode: 'group3_node2'
		},
		{
			id:'30',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromNode: 'group1_htmlNode1',
			toNode: 'group3_node3'
		},
		{
			id:'31',
			color: 'blue',
			type: 'orthogonal.horizontal',
			fromPosition: 'top.top',
			toPosition: 'top.top',
			splitPercent: 0,
			fromXoffset: -10,
			fromNode: 'group1_node5',
			toNode: 'group1_htmlNode1'
		},
	]
}